/**
 * pdf.js
 * Professional PDF and CSV Export for FinTrack PRO
 */

const ExportService = {
    toPDF: (transactions, accountType, settings) => {
        if (!window.jspdf || !window.jspdf.jsPDF) {
            showToast('PDF library not loaded.', 'error');
            return;
        }

        const { jsPDF } = window.jspdf;
        const doc = new jsPDF('landscape');
        const isDark = document.body.classList.contains('dark-theme');
        const pageWidth = doc.internal.pageSize.getWidth();
        const curr = settings.currency;

        // Header
        doc.setFontSize(22);
        doc.setTextColor(isDark ? 40 : 40);
        doc.text(`FinTrack PRO - ${capitalize(accountType)} Account Statement`, pageWidth / 2, 20, { align: 'center' });
        
        doc.setFontSize(10);
        doc.setTextColor(100);
        doc.text(`Generated: ${new Date().toLocaleString()}`, pageWidth / 2, 28, { align: 'center' });

        // Calculate Totals based on the passed transactions (might be filtered)
        let credit = 0, debit = 0;
        transactions.forEach(t => {
            if(t.type === 'credit') credit += parseFloat(t.amount);
            if(t.type === 'debit') debit += parseFloat(t.amount);
        });
        const balance = credit - debit;

        doc.setFontSize(11);
        doc.setTextColor(60);
        doc.text(`Total Credit (In): ${formatCurrency(credit, curr)}`, 14, 45);
        doc.text(`Total Debit (Out): ${formatCurrency(debit, curr)}`, 14, 52);
        doc.text(`Net Change: ${formatCurrency(balance, curr)}`, 14, 59);
        doc.text(`Total Records: ${transactions.length}`, pageWidth - 14, 45, { align: 'right' });

        // Table Data
        // Needs to be in chronological order with running balance
        const chronoTxns = calculateRunningBalances([...transactions]);

        const tableColumn = ["Date", "Txn ID", "Description", "Category", "Payment", "Credit", "Debit", "Balance"];
        const tableRows = chronoTxns.map(t => [
            formatDateOnly(t.date),
            t.id,
            t.description,
            t.category,
            t.paymentMethod,
            t.type === 'credit' ? formatCurrency(t.amount, curr) : '-',
            t.type === 'debit' ? formatCurrency(t.amount, curr) : '-',
            formatCurrency(t.runningBalance, curr)
        ]);

        doc.autoTable({
            startY: 70,
            head: [tableColumn],
            body: tableRows,
            theme: 'grid',
            headStyles: { fillColor: [37, 99, 235] }, // Primary Blue
            styles: { fontSize: 8, cellPadding: 2 },
            margin: { top: 70 }
        });

        // Footer Page Numbers
        const pageCount = doc.internal.getNumberOfPages();
        for(let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.text(`Page ${i} of ${pageCount} - Generated by FinTrack PRO`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
        }

        doc.save(`FinTrack_Statement_${accountType}_${new Date().toISOString().slice(0,10)}.pdf`);
        showToast('PDF Exported Successfully');
    },

    toCSV: (transactions, accountType) => {
        if (transactions.length === 0) {
            showToast('No data to export.', 'warning');
            return;
        }

        // Chronological order for CSV too
        const chronoTxns = calculateRunningBalances([...transactions]);
        const headers = ["Date", "Txn ID", "Type", "Category", "Description", "Payment Method", "Amount", "Running Balance", "Notes"];
        
        let csvContent = "data:text/csv;charset=utf-8," + headers.join(",") + "\r\n";

        chronoTxns.forEach(t => {
            const row = [
                t.date, t.id, t.type, t.category,
                `"${t.description.replace(/"/g, '""')}"`,
                t.paymentMethod, t.amount, t.runningBalance,
                `"${(t.notes || '').replace(/"/g, '""')}"`
            ];
            csvContent += row.join(",") + "\r\n";
        });

        const encodedUri = encodeURI(csvContent);
        const link = document.createElement("a");
        link.setAttribute("href", encodedUri);
        link.setAttribute("download", `FinTrack_${accountType}_${new Date().toISOString().slice(0,10)}.csv`);
        document.body.appendChild(link);
        link.click();
        link.remove();
        showToast('CSV Exported Successfully');
    }
};

window.ExportService = ExportService;
